;MAIN LAYOUT
$fMain = GUICreate($sAppTitle, 475, 600)
GUISetOnEvent($GUI_EVENT_CLOSE, "ApplicationClose")
GUISetFont(9, 400, 3, $sFont)
$bStart = GUICtrlCreateButton("Start", 4, 545, 100, 25)
GUICtrlSetOnEvent($bStart, "bStart")
$bStop = GUICtrlCreateButton("Stop", 110, 545, 100, 25)
GUICtrlSetState($bStop, $GUI_DISABLE)
GUICtrlSetOnEvent($bStop, "bStop")
$tRobotLog = GUICtrlCreateLabel("ClashBot Log:", 5, 5, 90, 17)
$tLog = _GUICtrlRichEdit_Create($fMain, "", 5, 25, 465, 200, BitOR($ES_MULTILINE, $ES_READONLY, $WS_VSCROLL, 8912))

;TAB LAYOUT
$tMain = GUICtrlCreateTab(5, 230, 465, 310)

;GENERAL TAB
$tpGeneral = GUICtrlCreateTabItem("General")
$gRobotSettings = GUICtrlCreateGroup("Robot Settings", 12, 255, 448, 73)
$cBoostBarracks = GUICtrlCreateCheckbox("Automatic Barracks Booster", 30, 275, 180, 17)
$cCollectResources = GUICtrlCreateCheckbox("Automatic Resource Collection", 30, 295, 200, 17)



;UNITS TAB
$tpUnits = GUICtrlCreateTabItem("Units")
$gUnitSettings = GUICtrlCreateGroup("Unit Settings", 12, 255, 448, 53)
$lUnitCapacity = GUICtrlCreateLabel("Troops Capacity:", 30, 275, 90, 17)
$lTownHall = GUICtrlCreateLabel("Town Hall:", 225, 275, 90, 17)
$tUnitCapacity = GUICtrlCreateInput("0", 120, 272, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
$cmTownHall = GUICtrlCreateCombo("", 315, 270, 50, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "1|2|3|4|5|6|7|8|9|10", "1")

$gTrainingSettings = GUICtrlCreateGroup("Training Settings", 12, 310, 448, 53)
$lTrainingCondition = GUICtrlCreateLabel("Training Condition:", 30, 330, 100, 17)
$cmTrainingCondition = GUICtrlCreateCombo("", 130, 325, 200, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Barbarian and Archers", "Barbarian and Archers")

$gUpgradeSettings = GUICtrlCreateGroup("Upgrade Settings", 12, 365, 448, 168)
$cUpgradeTarget1 = GUICtrlCreateCheckbox("Upgrade Target Building #1", 30, 385, 150, 17)
GUICtrlSetState($cUpgradeTarget1, $GUI_DISABLE)
$cUpgradeTarget2 = GUICtrlCreateCheckbox("Upgrade Target Building #2", 30, 415, 150, 17)
GUICtrlSetState($cUpgradeTarget2, $GUI_DISABLE)
$cUpgradeTarget3 = GUICtrlCreateCheckbox("Upgrade Target Building #3", 30, 445, 150, 17)
GUICtrlSetState($cUpgradeTarget3, $GUI_DISABLE)
$cUpgradeTarget4 = GUICtrlCreateCheckbox("Upgrade Target Building #4", 30, 475, 150, 17)
GUICtrlSetState($cUpgradeTarget4, $GUI_DISABLE)
$cUpgradeTarget5 = GUICtrlCreateCheckbox("Upgrade Target Building #5", 30, 505, 150, 17)
GUICtrlSetState($cUpgradeTarget5, $GUI_DISABLE)
$lGoldNeeded1 = GUICtrlCreateLabel("Gold:", 200, 386, 90, 17)
GUICtrlSetState($lGoldNeeded1, $GUI_DISABLE)
$lGoldNeeded2 = GUICtrlCreateLabel("Gold:", 200, 416, 90, 17)
GUICtrlSetState($lGoldNeeded2, $GUI_DISABLE)
$lGoldNeeded3 = GUICtrlCreateLabel("Gold:", 200, 446, 90, 17)
GUICtrlSetState($lGoldNeeded3, $GUI_DISABLE)
$lGoldNeeded4 = GUICtrlCreateLabel("Gold:", 200, 476, 90, 17)
GUICtrlSetState($lGoldNeeded4, $GUI_DISABLE)
$lGoldNeeded5 = GUICtrlCreateLabel("Gold:", 200, 506, 90, 17)
GUICtrlSetState($lGoldNeeded5, $GUI_DISABLE)
$tGoldNeeded1 = GUICtrlCreateInput("0", 240, 381, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState($tGoldNeeded1, $GUI_DISABLE)
$tGoldNeeded2 = GUICtrlCreateInput("0", 240, 411, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState($tGoldNeeded2, $GUI_DISABLE)
$tGoldNeeded3 = GUICtrlCreateInput("0", 240, 441, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState($tGoldNeeded3, $GUI_DISABLE)
$tGoldNeeded4 = GUICtrlCreateInput("0", 240, 471, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState($tGoldNeeded4, $GUI_DISABLE)
$tGoldNeeded5 = GUICtrlCreateInput("0", 240, 501, 56, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
GUICtrlSetState($tGoldNeeded5, $GUI_DISABLE)
$bUpgradeTarget1 = GUICtrlCreateButton("Find #1 Position", 320, 378, 100, 25)
GUICtrlSetState($bUpgradeTarget1, $GUI_DISABLE)
$bUpgradeTarget2 = GUICtrlCreateButton("Find #2 Position", 320, 408, 100, 25)
GUICtrlSetState($bUpgradeTarget2, $GUI_DISABLE)
$bUpgradeTarget3 = GUICtrlCreateButton("Find #3 Position", 320, 438, 100, 25)
GUICtrlSetState($bUpgradeTarget3, $GUI_DISABLE)
$bUpgradeTarget4 = GUICtrlCreateButton("Find #4 Position", 320, 468, 100, 25)
GUICtrlSetState($bUpgradeTarget4, $GUI_DISABLE)
$bUpgradeTarget5 = GUICtrlCreateButton("Find #5 Position", 320, 498, 100, 25)
GUICtrlSetState($bUpgradeTarget5, $GUI_DISABLE)



;MATCH TAB
$tpMatch = GUICtrlCreateTabItem("Match")
$gConditionSettings = GUICtrlCreateGroup("Condition Settings", 12, 255, 222, 108)
$cMeetGnE = GUICtrlCreateCheckbox("Meet Gold and Elixir", 30, 275, 150, 17)
$cMeetGoE = GUICtrlCreateCheckbox("Meet Gold or Elixir", 30, 295, 150, 17)
$cMeetDE = GUICtrlCreateCheckbox("Meet Dark Elixir", 30, 315, 150, 17)
$cMeetThOut = GUICtrlCreateCheckbox("Meet Town Hall Outside", 30, 335, 150, 17)

$gVariableSettings = GUICtrlCreateGroup("Variable Settings", 240, 255, 222, 108)
$lMinGold = GUICtrlCreateLabel("Minimum Gold: ", 258, 275, 105, 17)
$lMinElixir = GUICtrlCreateLabel("Minimum Elixir:", 258, 300, 105, 17)
$lMinDarkElixir = GUICtrlCreateLabel("Minimum Dark Elixir:", 258, 325, 105, 17)
$tMinGold = GUICtrlCreateInput("0", 373, 270, 61, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
$tMinElixir = GUICtrlCreateInput("0", 373, 295, 61, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))
$tMinDarkElixir = GUICtrlCreateInput("0", 373, 320, 61, 21, BitOR($GUI_SS_DEFAULT_INPUT, $ES_CENTER, $ES_NUMBER))

$gSearchSettings = GUICtrlCreateGroup("Search Settings", 12, 365, 449, 53)
$bStartSearch = GUICtrlCreateButton("Start Search", 30, 385, 100, 25)
GUICtrlSetOnEvent($bStartSearch, "bStartSearch")
$bContinueSearch = GUICtrlCreateButton("Continue Search", 135, 385, 100, 25)
GUICtrlSetState($bContinueSearch, $GUI_DISABLE)
GUICtrlSetOnEvent($bContinueSearch, "bContinueSearch")
$bStopSearch = GUICtrlCreateButton("Stop Search", 240, 385, 100, 25)
GUICtrlSetOnEvent($bStopSearch, "bStopSearch")



;ATTACK TAB
$tpAttack = GUICtrlCreateTabItem("Attack")
$gBehaviorSettings = GUICtrlCreateGroup("Behavior Settings", 12, 255, 448, 73)
$lAttackMode = GUICtrlCreateLabel("Attack Mode:", 30, 275, 90, 17)
$cmAttackMode = GUICtrlCreateCombo("", 130, 270, 200, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Active Mode|Non-Active Mode", "Active Mode")
$lAttackDeployment = GUICtrlCreateLabel("Deployment Mode:", 30, 300, 120, 17)
$cmAttackDeployment = GUICtrlCreateCombo("", 130, 295, 200, 25, BitOR($CBS_DROPDOWNLIST, $CBS_AUTOHSCROLL))
GUICtrlSetData(-1, "Random Spot Box Attack", "Random Spot Box Attack")

$gHeroSettings  = GUICtrlCreateGroup("Hero Settings", 12, 330, 448, 73)
$cEnableKing = GUICtrlCreateCheckbox("Enable Deployment of Barbarian King", 30, 350, 200, 17)
$cEnableQueen = GUICtrlCreateCheckbox("Enable Deployment of Archer Queen", 30, 370, 200, 17)



;DEVELOPMENT TAB
$tpDevelopment = GUICtrlCreateTabItem("Development")
$gLocationSettings = GUICtrlCreateGroup("Location Settings", 12, 255, 448, 140)
$bLocateTownHall = GUICtrlCreateButton("Locate Town Hall", 30, 275, 115, 25)
GUICtrlSetState($bLocateTownHall, $GUI_DISABLE)
$bLocateBarracks = GUICtrlCreateButton("Locate Barracks", 150, 275, 115, 25)
GUICtrlSetOnEvent($bLocateBarracks, "bLocateBarracks")
$bLocateCollectors = GUICtrlCreateButton("Locate Collectors", 270, 275, 115, 25)
GUICtrlSetOnEvent($bLocateCollectors, "bLocateCollectors")
$bLocateTraps = GUICtrlCreateButton("Locate Traps", 30, 305, 115, 25)
GUICtrlSetState($bLocateTraps, $GUI_DISABLE)
$bLocateCannons = GUICtrlCreateButton("Locate Cannons", 150, 305, 115, 25)
GUICtrlSetState($bLocateCannons, $GUI_DISABLE)
$bLocateArcherTowers = GUICtrlCreateButton("Locate Archer Towers", 270, 305, 115, 25)
GUICtrlSetState($bLocateArcherTowers, $GUI_DISABLE)
$bLocateMortars = GUICtrlCreateButton("Locate Mortars", 30, 335, 115, 25)
GUICtrlSetState($bLocateMortars, $GUI_DISABLE)
$bLocateWizardTowers = GUICtrlCreateButton("Locate Wizard Towers", 150, 335, 115, 25)
GUICtrlSetState($bLocateWizardTowers, $GUI_DISABLE)
$bLocateAirDefenses = GUICtrlCreateButton("Locate Air Defenses", 270, 335, 115, 25)
GUICtrlSetState($bLocateAirDefenses, $GUI_DISABLE)
$bLocateHiddenTeslas = GUICtrlCreateButton("Locate Hidden Teslas", 30, 365, 115, 25)
GUICtrlSetState($bLocateHiddenTeslas, $GUI_DISABLE)
$bLocateXBow = GUICtrlCreateButton("Locate X-Bow", 150, 365, 115, 25)
GUICtrlSetState($bLocateXBow, $GUI_DISABLE)
$bLocateInfernoTowers = GUICtrlCreateButton("Locate Inferno Towers", 270, 365, 115, 25)
GUICtrlSetState($bLocateInfernoTowers, $GUI_DISABLE)

$gCreatorSettings = GUICtrlCreateGroup("Creator Settings", 12, 395, 448, 115)
$bClickArea = GUICtrlCreateButton("Click An Area", 30, 415, 115, 25)
GUICtrlSetOnEvent($bClickArea, "bClickArea")
$bSearchImage = GUICtrlCreateButton("Search Image", 150, 415, 115, 25)
GUICtrlSetOnEvent($bSearchImage, "bSearchImage")
$bAttack = GUICtrlCreateButton("Attack", 270, 415, 115, 25)
GUICtrlSetOnEvent($bAttack, "bAttack")
$cCaptureConditionMatch = GUICtrlCreateCheckbox("Take All Town Hall Snapshots When Condition Match", 30, 445, 300, 17)
$cCaptureConditionNotMatch = GUICtrlCreateCheckbox("Take All Town Hall Snapshots When Condition Did Not Match", 30, 465, 350, 17)
$cCaptureLoot = GUICtrlCreateCheckbox("Take All Loots Taken Snapshots", 30, 485, 200, 17)

GUISetState(@SW_SHOW, $fMain)